### ISSUE TITLE
Use Proxy type for type info?

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-quickcheck-laws#1]
First off, this looks fantastic.

I just noticed you're using things like an unused `m a` in the `Bind` check, to infer the type info. Maybe a set of `Proxy` types would be an improvement, since you might not even be able to produce a value of type `m a` easily.

**Comment by garyb** [comment]
Ah, you noticed this :) I was going to open an issue asking for review anyway.

Yeah, I was thinking of something like that too. Where would be a good place for the `Proxy` type to live? I made one in `affjax` too, but having an entire library for it perhaps seems overkill? Maybe not.

I wasn't sure about the utility of the tests for `Semigroupoid` and `Category` too, seems it might be a little hard to produce values for those that are testable due to the `Eq (a b e)` constraint, as obviously that won't work for `(->)`, for example.

**Comment by paf31** [comment]
The issue is that `Proxy` is naturally poly-kinded, which we can't do right now. Some kind of `purescript-proxy` library wouldn't be a bad idea though.

I was wondering if it would be possible to introduce some fake types to take the place of the `a`, `b`, `c`, etc. in tests. For `Monad`, for example, you don't care what `a` is, just `m`. So we could make an enum type with say, 20 inhabitants or something, and just use that every time.

**Comment by garyb** [comment]
Yeah, maybe I'll do that for now then, make a tiny library and include `Proxy2`, `Proxy3` etc.

Agreed on the `Monad` stuff too. Could just use `unit` for that I guess?

**Comment by garyb** [comment]
Actually I guess `unit` isn't good enough, it could easily hide problems.
